name: my-surface-os
description: Personal Fedora Silverblue image optimized for Microsoft Surface.

base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: latest

modules:
  # 1. Manage native packages via rpm-ostree
  - type: rpm-ostree
    install:
      - vim
      - gnome-shell-extension-appindicator
      - chezmoi

  # 2. Ensure system flatpaks update cleanly
  - type: default-flatpaks
    configurations:
        - notify: true
