name: my-surface-os
description: Personal Fedora Silverblue image optimized for Microsoft Surface.

base-image: ghcr.io/ublue-os/bazzite-gnome-nvidia
image-version: 44

modules:
  # 1. Manage native packages via rpm-ostree
  - type: rpm-ostree
    repos:
      # Add the official Google Chrome repository
      - https://dl.google.com/linux/chrome/rpm/stable/x86_64
    install:
      - vim
      - google-chrome-stable
      - gnome-shell-extension-appindicator
      - chezmoi
    remove:
      - firefox
      - firefox-langpacks

  # 2. Ensure system flatpaks update cleanly
  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.slack.Slack
        - be.alexandervanhee.gradia
      remove: []
