name: Build and Push Custom OS Image
on:
  schedule:
    - cron: "0 0 * * 1" # Automatically rebuild every Monday at midnight to pull latest security patches
  push:
    branches:
      - master
    paths:
      - 'config/**'
      - '.github/workflows/**'
  workflow_dispatch: # Allows you to manually click "Run Workflow" in the GitHub UI

env:
  IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      # Use the official BlueBuild compiler tool
      - name: Build Custom Image
        uses: blue-build/github-action@v1
        with:
          recipe: 'config/recipe.yml'
          registry_token: ${{ github.token }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
